package unitec.rpg.entities.enums;

public enum Statuses {

    POISONED, BURNED, FROZEN, PARALYZED, ASLEEP, CONFUSED, SLOWED, HASTENED, SHIELDED,
    INVISIBLE, INVINCIBLE, WEAKENED,
    STRENGTHENED, CURSED, BLESSED, STUNNED, SILENCED, BLINDED;
}
